const now = Date.now();

export const sampleState = {
  rules: [
    {
      id: "rule-guide",
      title: "Launch Guide Reel",
      mediaId: "178900001",
      keyword: "GUIDE",
      message: "Thanks for commenting. Here is the guide link you asked for.",
      active: true,
      createdAt: new Date(now - 1000 * 60 * 60 * 24 * 4).toISOString(),
      updatedAt: new Date(now - 1000 * 60 * 60 * 24).toISOString(),
    },
    {
      id: "rule-pricing",
      title: "Pricing Breakdown Post",
      mediaId: "178900002",
      keyword: "PRICE",
      message: "Here are the pricing details. Reply here if you want help choosing a plan.",
      active: true,
      createdAt: new Date(now - 1000 * 60 * 60 * 24 * 3).toISOString(),
      updatedAt: new Date(now - 1000 * 60 * 60 * 12).toISOString(),
    },
    {
      id: "rule-workshop",
      title: "Weekend Workshop Reel",
      mediaId: "178900003",
      keyword: "WORKSHOP",
      message: "You are on the list. I sent the workshop details to your inbox.",
      active: false,
      createdAt: new Date(now - 1000 * 60 * 60 * 24 * 2).toISOString(),
      updatedAt: new Date(now - 1000 * 60 * 60 * 6).toISOString(),
    },
  ],
  comments: [
    {
      id: "comment-1",
      username: "maya_studio",
      mediaId: "178900001",
      postTitle: "Launch Guide Reel",
      text: "GUIDE please",
      status: "new",
      receivedAt: new Date(now - 1000 * 60 * 9).toISOString(),
      sentAt: null,
      ignoredAt: null,
    },
    {
      id: "comment-2",
      username: "growthwithavi",
      mediaId: "178900002",
      postTitle: "Pricing Breakdown Post",
      text: "Can you send PRICE",
      status: "new",
      receivedAt: new Date(now - 1000 * 60 * 28).toISOString(),
      sentAt: null,
      ignoredAt: null,
    },
    {
      id: "comment-3",
      username: "content_nisha",
      mediaId: "178900003",
      postTitle: "Weekend Workshop Reel",
      text: "Workshop details?",
      status: "new",
      receivedAt: new Date(now - 1000 * 60 * 49).toISOString(),
      sentAt: null,
      ignoredAt: null,
    },
    {
      id: "comment-4",
      username: "brandops",
      mediaId: "178900002",
      postTitle: "Pricing Breakdown Post",
      text: "PRICE",
      status: "sent",
      receivedAt: new Date(now - 1000 * 60 * 92).toISOString(),
      sentAt: new Date(now - 1000 * 60 * 88).toISOString(),
      ignoredAt: null,
    },
  ],
  logs: [
    {
      id: "log-1",
      type: "dm_sent",
      status: "sent",
      message: "DM sent to brandops for keyword PRICE.",
      username: "brandops",
      mediaId: "178900002",
      keyword: "PRICE",
      commentId: "comment-4",
      createdAt: new Date(now - 1000 * 60 * 88).toISOString(),
    },
    {
      id: "log-2",
      type: "comment_matched",
      status: "matched",
      message: "Comment from maya_studio matched keyword GUIDE.",
      username: "maya_studio",
      mediaId: "178900001",
      keyword: "GUIDE",
      commentId: "comment-1",
      createdAt: new Date(now - 1000 * 60 * 9).toISOString(),
    },
  ],
  settings: {
    metaAppId: "",
    accessToken: "",
    webhookUrl: "",
    webhookVerifyToken: "",
    autoSend: false,
    reduceMotion: false,
    compactTables: false,
  },
};
